apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-inference
  template:
    metadata:
      labels:
        app: iris-inference
    spec:
      containers:
      - name: iris-inference
        image: us-central1-docker.pkg.dev/project-72f1e089-301b-4e5c-b15/iris-repo-mlops/iris-inference-mlops-week-7:latest
        ports:
          - containerPort: 8100
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"