name: CD to GKE

on:
  push:
    branches:
      - week_7

env:
  IMAGE: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/iris-inference-mlops-week-7:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

      
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin

      - run: gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}-docker.pkg.dev --quiet

      - run: docker build -t $IMAGE .

      - run: docker push $IMAGE

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: kubectl apply -f k8s/

      - run: kubectl set image deployment/iris-inference iris-inference=$IMAGE

      - run: kubectl rollout status deployment/iris-inference --timeout=5m

      - name: Install wrk
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wrk

      - name: Get External IP
        run: |
          echo "Waiting for external IP..."
          for i in $(seq 1 20); do
            IP=$(kubectl get svc iris-inference-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [ -n "$IP" ]; then
              echo "EXTERNAL_IP=$IP" >> $GITHUB_ENV
              echo "Found IP: $IP"
              break
            fi
            echo "Attempt $i: IP not ready, retrying in 15s..."
            sleep 15
          done

      - name: Run wrk stress test
        run: |
          cat > /tmp/post.lua << 'EOF'
          wrk.method = "POST"
          wrk.headers["Content-Type"] = "application/json"
          wrk.body = '{"sepal_length":5.1,"sepal_width":3.5,"petal_length":1.4,"petal_width":0.2}'
          EOF

          echo "Running stress test against http://$EXTERNAL_IP/predict/"
          wrk -t4 -c1000 -d30s -s /tmp/post.lua http://$EXTERNAL_IP/predict/